title: Carlos' blog
description: >-
  A blog about how to do the right type of philosophy :)  
baseurl: "/blog"
url: "charlesdka.github.io/blog/"
github_username:  CharlesDKA

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
  date_format: "%d %B, %Y"

google_analytics: UA-24316761-2

collections:
  drafts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: ""
      type: drafts
    values:
      sitemap: false
      noindex: true